#!/bin/bash
# GPU Detection and .env.gpu Generation Script
# Detects system GPU capabilities and generates .env.gpu configuration
# Called automatically during zero-touch installation

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
ENV_GPU_FILE="$PROJECT_ROOT/.env.gpu"

log_info() { echo -e "\033[0;34m[INFO]\033[0m $1"; }
log_success() { echo -e "\033[0;32m[SUCCESS]\033[0m $1"; }
log_warning() { echo -e "\033[1;33m[WARNING]\033[0m $1"; }

# Start generation
log_info "Detecting GPU and generating .env.gpu..."

# Initialize variables
GPU_TYPE="cpu"
GPU_COUNT=0
CUDA_VERSION=""
CUDNN_VERSION=""
JAX_PLATFORM="cpu"

# Detect NVIDIA CUDA
if command -v nvidia-smi &> /dev/null; then
    log_info "NVIDIA GPU detected"
    GPU_TYPE="cuda"
    GPU_COUNT=$(nvidia-smi --list-gpus 2>/dev/null | wc -l || echo "0")
    CUDA_VERSION=$(nvidia-smi --query-gpu=driver_version --format=csv,noheader | head -1 2>/dev/null || echo "unknown")
    JAX_PLATFORM="gpu"
    log_success "Found $GPU_COUNT NVIDIA GPU(s), CUDA driver version: $CUDA_VERSION"
fi

# Detect Apple Metal (macOS)
if [[ "$OSTYPE" == "darwin"* ]]; then
    if system_profiler SPDisplaysDataType | grep -q "Metal"; then
        log_info "Apple Metal GPU detected"
        GPU_TYPE="metal"
        GPU_COUNT=1
        JAX_PLATFORM="gpu"
        log_success "Apple Metal GPU available"
    fi
fi

# Detect AMD ROCm (optional future support)
if command -v rocm-smi &> /dev/null 2>&1; then
    log_info "AMD ROCm GPU detected"
    GPU_TYPE="rocm"
    GPU_COUNT=$(rocm-smi --showid 2>/dev/null | grep -c "GPU" || echo "0")
    JAX_PLATFORM="gpu"
    log_success "Found $GPU_COUNT AMD GPU(s) via ROCm"
fi

# Detect CPU info
CPU_COUNT=$(nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || echo "4")
CPU_TOTAL_MEM=$(free -h 2>/dev/null | grep Mem | awk '{print $2}' || echo "unknown")

# Determine memory fraction for GPU
if [ "$GPU_COUNT" -gt 0 ]; then
    MEM_FRACTION="0.85"  # Conservative for shared GPU memory
else
    MEM_FRACTION="0.0"   # CPU-only
fi

# Determine XLA threads
XLA_THREADS=$((CPU_COUNT * 2))
OMP_THREADS=$CPU_COUNT

# Generate .env.gpu
cat > "$ENV_GPU_FILE" << EOF
# Auto-generated GPU Configuration
# Generated: $(date)
# Do not edit this file directly - regenerate with: scripts/detect_gpu_and_generate_env.sh

# GPU Detection Results
GPU_TYPE=$GPU_TYPE
GPU_COUNT=$GPU_COUNT
CUDA_VERSION=$CUDA_VERSION
CPU_COUNT=$CPU_COUNT
SYSTEM_MEMORY=$CPU_TOTAL_MEM

# GPU Optimization Settings
ENABLE_GPU_OPTIMIZATION=true
JAX_PLATFORMS=$JAX_PLATFORM

# XLA/CUDA Optimization
TF_XLA_CACHE_DIR=\${HOME}/.cache/jax/xla_cache
XLA_PYTHON_CLIENT_MEM_FRACTION=$MEM_FRACTION
XLA_FLAGS="--xla_gpu_fuse_operations=true --xla_gpu_kernel_lazy_compilation_threshold=10000 --xla_gpu_enable_cudnn_frontend=true"

# Thread Pool Configuration
OMP_NUM_THREADS=$OMP_THREADS
TF_NUM_INTRAOP_THREADS=$OMP_THREADS
TF_NUM_INTEROP_THREADS=$((OMP_THREADS / 2))

# JAX Configuration
JAX_DEVICE_COUNT=$GPU_COUNT
JAX_CUDA_VISIBLE_DEVICES="0"

# Model Optimization
ENABLE_JIT_WARMUP=true
ENABLE_OPERATION_FUSION=true

# Server Profiling (optional)
# PROFILE_INFERENCE=false

# Advanced Options (uncomment to customize)
# XLA_COMPILER_OPTIMIZATION_LEVEL=3
# TF_FORCE_GPU_ALLOW_GROWTH=true
# TF_CPP_MIN_LOG_LEVEL=2
EOF

log_success "Configuration written to: $ENV_GPU_FILE"

# Show summary
echo ""
echo "GPU Configuration Summary:"
echo "  GPU Type:           $GPU_TYPE"
echo "  GPU Count:          $GPU_COUNT"
echo "  CPU Cores:          $CPU_COUNT"
echo "  System Memory:      $CPU_TOTAL_MEM"
echo "  Memory Fraction:    $MEM_FRACTION"
echo "  JAX Platform:       $JAX_PLATFORM"
echo ""
echo "To activate this configuration, run:"
echo "  source scripts/activate_gpu_optimizations.sh"
echo ""
