name: ARM64 Platform Validation

on:
  push:
    branches: [ main, develop ]
    paths:
      - '.github/workflows/arm64-validation.yml'
      - 'deploy/docker-compose*.yaml'
      - '*.sh'
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      test_mode:
        description: 'Test mode to run'
        required: true
        default: 'quick'
        type: choice
        options:
        - quick
        - full
        - docker-only
        - native-only

jobs:
  validate-arm64:
    runs-on: [self-hosted, ARM64, gpu]
    timeout-minutes: 60
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Platform Detection
      id: platform
      run: |
        echo "=== Platform Detection ==="
        ARCH=$(uname -m)
        echo "Architecture: $ARCH"
        echo "arch=$ARCH" >> $GITHUB_OUTPUT
        
        if [ "$ARCH" = "aarch64" ] || [ "$ARCH" = "arm64" ]; then
          echo "Platform: ARM64 (native)"
          echo "is_arm64=true" >> $GITHUB_OUTPUT
        else
          echo "Platform: $ARCH (not ARM64)"
          echo "is_arm64=false" >> $GITHUB_OUTPUT
        fi
        
        # Check OS
        if [ -f /etc/os-release ]; then
          . /etc/os-release
          echo "OS: $NAME $VERSION_ID"
          echo "os_name=$NAME" >> $GITHUB_OUTPUT
          echo "os_version=$VERSION_ID" >> $GITHUB_OUTPUT
        fi
        
        # Check kernel
        echo "Kernel: $(uname -r)"
        echo "kernel=$(uname -r)" >> $GITHUB_OUTPUT
        echo
        
    - name: Validate ARM64 System
      if: steps.platform.outputs.is_arm64 == 'true'
      run: |
        echo "=== ARM64 System Validation ==="
        
        # CPU information
        echo "CPU Information:"
        lscpu | grep -E "Architecture|CPU|Thread|Core|Socket|Model name"
        echo
        
        # Memory
        echo "Memory Information:"
        free -h
        echo
        
        # GPU
        echo "GPU Information:"
        if command -v nvidia-smi >/dev/null 2>&1; then
          nvidia-smi --query-gpu=index,name,driver_version,memory.total,compute_cap --format=csv
        else
          echo "No NVIDIA GPU detected"
        fi
        echo
        
    - name: Docker Platform Support Check
      run: |
        echo "=== Docker Platform Support ==="
        
        # Docker version
        docker --version
        docker compose version
        echo
        
        # Check Docker buildx
        echo "Docker Buildx Platforms:"
        docker buildx ls
        echo
        
        # Check if QEMU is available for emulation
        if docker run --rm --privileged multiarch/qemu-user-static --version >/dev/null 2>&1; then
          echo "QEMU emulation: Available"
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        else
          echo "QEMU emulation: Not available"
        fi
        echo
        
    - name: Test ARM64 Native Container
      run: |
        echo "=== Testing ARM64 Native Container ==="
        
        # Test basic ARM64 container
        docker run --rm --platform=linux/arm64 ubuntu:22.04 bash -c "
          echo 'Container architecture:' && uname -m
          echo 'OS:' && cat /etc/os-release | grep PRETTY_NAME
          echo 'Python:' && apt-get update -qq && apt-get install -y -qq python3 && python3 --version
        "
        
        echo "ARM64 native container test: PASSED"
        echo
        
    - name: Test AMD64 Emulation
      run: |
        echo "=== Testing AMD64 Emulation ==="
        
        # Test AMD64 container with emulation
        docker run --rm --platform=linux/amd64 ubuntu:22.04 bash -c "
          echo 'Container architecture:' && uname -m
          echo 'OS:' && cat /etc/os-release | grep PRETTY_NAME
          echo 'Testing emulation performance...'
          time python3 -c 'sum(range(1000000))' 2>&1 | grep real || true
        " || echo "AMD64 emulation test: FAILED"
        
        echo "AMD64 emulation test: COMPLETED"
        echo
        
    - name: Test NVIDIA Container Runtime
      if: steps.platform.outputs.is_arm64 == 'true'
      run: |
        echo "=== Testing NVIDIA Container Runtime ==="
        
        # Test GPU access in ARM64 container
        docker run --rm --gpus all --platform=linux/arm64 ubuntu:22.04 bash -c "
          apt-get update -qq
          apt-get install -y -qq cuda-toolkit-12-3 || apt-get install -y -qq nvidia-cuda-toolkit || true
          if command -v nvidia-smi >/dev/null 2>&1; then
            nvidia-smi
          else
            echo 'nvidia-smi not available in container'
          fi
        " || echo "GPU test in ARM64 container: FAILED"
        
        echo "NVIDIA container runtime test: COMPLETED"
        echo
        
    - name: Test Docker Compose Validation
      if: ${{ github.event.inputs.test_mode != 'native-only' }}
      run: |
        echo "=== Docker Compose Validation ==="
        
        # Validate main docker-compose file
        if [ -f "deploy/docker-compose.yaml" ]; then
          echo "Validating docker-compose.yaml:"
          docker compose -f deploy/docker-compose.yaml config > /tmp/compose-config.yaml
          echo "✓ docker-compose.yaml is valid"
          
          # Check platform specifications
          echo "Platform specifications:"
          grep -E "platform:|image:" deploy/docker-compose.yaml | head -20
        fi
        
        # Validate single GPU compose file
        if [ -f "deploy/docker-compose-single-gpu.yaml" ]; then
          echo "Validating docker-compose-single-gpu.yaml:"
          docker compose -f deploy/docker-compose-single-gpu.yaml config > /tmp/compose-single-config.yaml
          echo "✓ docker-compose-single-gpu.yaml is valid"
        fi
        
        echo
        
    - name: Test Python Environment Setup
      if: ${{ github.event.inputs.test_mode != 'docker-only' }}
      run: |
        echo "=== Python Environment Setup ==="
        
        # Create virtual environment
        if [ ! -d ".venv" ]; then
          python3 -m venv .venv
        fi
        
        source .venv/bin/activate
        
        # Upgrade pip
        pip install --upgrade pip
        
        # Install requirements
        if [ -f "requirements.txt" ]; then
          pip install -r requirements.txt
          echo "✓ Requirements installed"
        fi
        
        # Verify installations
        echo "Installed packages:"
        pip list
        
        # Test imports
        python3 -c "
import sys
import platform
print(f'Python version: {sys.version}')
print(f'Platform: {platform.machine()}')
print(f'Python implementation: {platform.python_implementation()}')

# Test key packages
try:
    import jupyter
    print(f'✓ Jupyter: {jupyter.__version__}')
except ImportError as e:
    print(f'✗ Jupyter: {e}')

try:
    import requests
    print(f'✓ Requests: {requests.__version__}')
except ImportError as e:
    print(f'✗ Requests: {e}')

try:
    import numpy as np
    print(f'✓ NumPy: {np.__version__}')
except ImportError as e:
    print(f'✗ NumPy: {e}')
"
        echo
        
    - name: Test Conda/Mamba Setup (Optional)
      if: ${{ github.event.inputs.test_mode == 'full' || github.event.inputs.test_mode == 'native-only' }}
      run: |
        echo "=== Conda/Mamba Setup Test ==="
        
        # Check if miniforge is installed
        if [ -d "$HOME/miniforge3" ]; then
          echo "Miniforge found at $HOME/miniforge3"
          source $HOME/miniforge3/bin/activate
          
          echo "Conda version: $(conda --version)"
          echo "Mamba version: $(mamba --version 2>/dev/null || echo 'not installed')"
          
          echo "Conda environments:"
          conda env list
        else
          echo "Miniforge not installed (optional for this test)"
        fi
        echo
        
    - name: Verify Shell Scripts
      run: |
        echo "=== Shell Scripts Verification ==="
        
        # Check shell scripts exist and are executable
        scripts=(
          "setup_local.sh"
          "setup_github_runner.sh"
          "check_runner_status.sh"
          "deploy/run_single_gpu.sh"
        )
        
        for script in "${scripts[@]}"; do
          if [ -f "$script" ]; then
            if [ -x "$script" ]; then
              echo "✓ $script: exists and executable"
            else
              echo "✗ $script: exists but not executable"
              chmod +x "$script"
              echo "  → Made executable"
            fi
          else
            echo "✗ $script: not found"
          fi
        done
        echo
        
    - name: Generate ARM64 Compatibility Report
      if: always()
      run: |
        cat > arm64_validation_report.txt << EOF
=== ARM64 Platform Validation Report ===
Generated: $(date)
Workflow Run: ${{ github.run_number }}
Test Mode: ${{ github.event.inputs.test_mode || 'quick' }}

== System Information ==
Architecture: ${{ steps.platform.outputs.arch }}
OS: ${{ steps.platform.outputs.os_name }} ${{ steps.platform.outputs.os_version }}
Kernel: ${{ steps.platform.outputs.kernel }}
Is ARM64: ${{ steps.platform.outputs.is_arm64 }}

== Hardware ==
CPU Cores: $(nproc)
Memory: $(free -h | awk '/^Mem:/{print $2}')
EOF

        if command -v nvidia-smi >/dev/null 2>&1; then
          echo "GPU: $(nvidia-smi --query-gpu=name --format=csv,noheader | head -1)" >> arm64_validation_report.txt
          echo "GPU Driver: $(nvidia-smi --query-gpu=driver_version --format=csv,noheader | head -1)" >> arm64_validation_report.txt
        else
          echo "GPU: Not available" >> arm64_validation_report.txt
        fi

        cat >> arm64_validation_report.txt << EOF

== Docker ==
Docker Version: $(docker --version)
Compose Version: $(docker compose version)

== Platform Support ==
ARM64 Native Containers: Supported
AMD64 Emulation: $(docker run --rm --platform=linux/amd64 ubuntu:22.04 echo "Supported" 2>/dev/null || echo "Not Supported")

== Test Results ==
All critical tests completed. See workflow logs for details.

== Recommendations ==
EOF

        if [ "${{ steps.platform.outputs.is_arm64 }}" = "true" ]; then
          cat >> arm64_validation_report.txt << EOF
✓ System is ARM64 - optimal for native ARM64 workflows
- Use native installation workflows for best performance
- Docker containers will use AMD64 emulation for NVIDIA NIM
- Consider hybrid approach: native tools + Docker for unavailable components
EOF
        else
          cat >> arm64_validation_report.txt << EOF
✗ System is not ARM64 (${{ steps.platform.outputs.arch }})
- ARM64-specific optimizations will not apply
- Use standard Docker workflows without emulation
EOF
        fi

        cat arm64_validation_report.txt
        echo
        
    - name: Upload Validation Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: arm64-validation-report-${{ github.run_number }}
        path: arm64_validation_report.txt
        retention-days: 30
        
    - name: Summary
      if: always()
      run: |
        echo "=== ARM64 Validation Summary ==="
        echo "Architecture: ${{ steps.platform.outputs.arch }}"
        echo "Is ARM64: ${{ steps.platform.outputs.is_arm64 }}"
        echo "Test Mode: ${{ github.event.inputs.test_mode || 'quick' }}"
        echo
        
        if [ "${{ steps.platform.outputs.is_arm64 }}" = "true" ]; then
          echo "✅ ARM64 platform validation: PASSED"
          echo "System is ready for ARM64 workflows"
        else
          echo "ℹ️  Platform is ${{ steps.platform.outputs.arch }}"
          echo "ARM64-specific features not applicable"
        fi
